# Generated by Django 5.2.5 on 2025-09-01 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='especialidade',
            fields=[
                ('id_especialidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nascimento', models.DateField()),
                ('crm', models.CharField(max_length=50, unique=True)),
                ('id_especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='medico.especialidade')),
            ],
        ),
    ]
