# Generated by Django 5.2.5 on 2025-09-18 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='id_especialidade',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='medico.especialidade'),
            preserve_default=False,
        ),
    ]
